name: "Test"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v31
    - run: nix flake check
    - run: nix develop .#ci -c clang-format -Werror --dry-run $(find app rt -regex ".*\.\(h\|c\|cpp\)$")
    - run: nix develop .#ci -c ormolu --mode check $(find app -name "*.hs")
    - run: nix develop .#ci -c cabal-fmt --check *.cabal
    - run: nix develop .#ci -c make run
    - run: nix develop .#ci -c cabal update
    - run: nix develop .#ci -c cabal run
